### ISSUE TITLE
List and card views with buttons at the top

### ISSUE THREAD

**Issue by hauswio** [JaimeStill/telebook-proto#3]
Similar to a file browser, having the list and cards as different views.

**Comment by JaimeStill** [comment]
Implemented along with an initial user preferences integration. See [live prototype site](https://jaimestill.github.io/telebook-proto/) for details. Whenever you toggle the layout or select a new page size, it will store your preferences in local storage and use the preferred layout the next time you load the view.

The [layout component](https://github.com/JaimeStill/telebook-proto/blob/main/src/app/core/components/layout.component.ts) that's wrapping all of this has been pretty well abstracted to work for any collection of data. It wouldn't be too difficult in the long run to abstract grid and list layouts that work for any data structure.

**Comment by hauswio** [comment]
epic. looks great.
